jobs:
  action:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./workflow/test

name: Verify

on:
  schedule:
    - cron: "55 */3 * * *"
